name: build-prod

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -la

      - name: Update version
        run: |
          sed -i "s/GH Actions Run Number: .*/GH Actions Run Number: ${{ github.run_number }}/" README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update run number [skip ci]"
          git push origin